### ISSUE TITLE
Small error regarding the maximum size of a DS file on Audio.html page

### ISSUE THREAD

**Issue by NotImplementedLife** [BowersIndustry/ds-creator-docs#1]
_Since DS homebrew games can only be 4kb big, I had to not use a library that let's you use .mp3 music, so there is more room for code._

The limit for a usual homebrew DS ROM is 4MB, the size of the console's EWRAM.

**Comment by BowersIndustry** [comment]
Sorry it took so long to respond...
Thanks for the correction!
